CREATE TABLE rbac_role (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR2(255) NOT NULL UNIQUE,
    description VARCHAR2(1024)
)

CREATE TABLE rbac_role_permission (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id     NUMBER NOT NULL REFERENCES rbac_role(id) ON DELETE CASCADE,
    permission  VARCHAR2(255) NOT NULL,
    CONSTRAINT uq_role_perm UNIQUE (role_id, permission)
)

CREATE TABLE rbac_user_role (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     NUMBER NOT NULL UNIQUE,
    role_id     NUMBER NOT NULL REFERENCES rbac_role(id) ON DELETE CASCADE
)

CREATE TABLE rbac_role_channel (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id     NUMBER NOT NULL REFERENCES rbac_role(id) ON DELETE CASCADE,
    channel_id  CHAR(36) NOT NULL,
    CONSTRAINT uq_role_chan UNIQUE (role_id, channel_id)
)
